/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on Jan 15, 2016, 2:06:34 PM
 */

package manage;
import java.sql.*;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {
public DatabaseTest_1 dt;

    /** Creates new form Home */

    public Home(Login pd,DatabaseTest_1 dt) {
        this.pd=pd;
        this.dt=dt;
        initComponents();
    }




    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(manage.ManageApp.class).getContext().getResourceMap(Home.class);
        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMinimumSize(new java.awt.Dimension(350, 450));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 60, 120, 40);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setForeground(resourceMap.getColor("jButton2.foreground")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 60, 170, 40);

        jButton3.setFont(resourceMap.getFont("jButton3.font")); // NOI18N
        jButton3.setForeground(resourceMap.getColor("jButton3.foreground")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 221, 100, 40);

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 160);

        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 160, 220, 180);

        jLabel5.setIcon(resourceMap.getIcon("jLabel5.icon")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 0, 210, 160);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(2000, 1080));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 420, 310);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Profile p=new Profile(pd,dt );
       this.setVisible(false);
       p.setVisible(true);
       try{
            ResultSet rs=dt.dbc.searchDB("select * from System where NID='"+pd.NID+"'");
            while(rs.next()){
                NID=rs.getString("NID");
                Username=rs.getString("Username");
                Password=rs.getString("Password");
                Secw=rs.getString("Secw");
                Contact=rs.getString("Contact");
                Email=rs.getString("Email");
                Gender=rs.getString("Gender");

               


                System.out.println(Contact);
            }
            rs.close();
            p.jTextField5.setText(NID);
            p.jTextField6.setText(Username);
            p.jTextField7.setText(Password);
            p.jTextField1.setText(Secw);
            p.jTextField8.setText(Contact);
            p.jTextField2.setText(Email);
            p.jTextField3.setText(Gender);

       }catch(Exception s){System.out.println("Dint found");}  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UpdateWindow uw=new UpdateWindow(pd,dt);
         this.setVisible(false);
         uw.setVisible(true);
         uw.jLabel2.setText(pd.NID);
         // System.out.println("one last "+ pd.NID);


       
       try{
            ResultSet rs=dt.dbc.searchDB("select * from System where NID='"+pd.NID+"'");
            while(rs.next()){
                NID=rs.getString("NID");
                Username=rs.getString("Username");
                Password=rs.getString("Password");
                Secw=rs.getString("Secw");
                Contact=rs.getString("Contact");
                Email=rs.getString("Email");
                Gender=rs.getString("Gender");




                System.out.println(Contact);
            }
            rs.close();
            uw.jTextField7.setText(NID);
            uw.jTextField8.setText(Username);
            uw.jTextField9.setText(Password);
            uw.jTextField10.setText(Secw);
            uw.jTextField11.setText(Contact);
            uw.jTextField12.setText(Email);
            uw.jTextField13.setText(Gender);

       }catch(Exception s){System.out.println("Dint found");}
         System.out.println("one last "+ pd.NID);
 
 


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         m.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments

    */
     public Login pd;
   // public DatabaseTest_1 dt;
    String NID=new String();
    String Username=new String();
    String Password=new String();
    String Secw=new String();
    String Contact=new String();
    String Email=new String();
    String Gender=new String();
     Login m=new Login();


    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;

    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;

    

/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
*/
}
